services:
    engage360d_pages.form.menu:
        factory_service: form.factory
        factory_method: createNamed
        class: Symfony\Component\Form\Form
        arguments: ["user", "engage360d_pages_menu", null, { }]
        tags:
            - { name: rest.form, route: post_menu }
            - { name: rest.form, route: put_menu }

    engage360d_pages.form.menu.type:
        class: Engage360d\Bundle\PagesBundle\Form\Type\MenuFormType
        arguments: [%engage360d_pages.entity.menu.class%]
        tags:
            - { name: form.type, alias: engage360d_pages_menu }
