parameters:
    engage360d_pages.manager.page.class: Engage360d\Bundle\PagesBundle\Entity\Page\PageManager

services:
    engage360d_pages.manager.page:
        class: %engage360d_pages.manager.page.class%
        arguments:
            - @engage360d_pages.entity_manager.page
            - %engage360d_pages.entity.page.class%
        tags:
            - { name: rest.entity_manager, route: get_pages }
            - { name: rest.entity_manager, route: post_pages }
            - { name: rest.entity_manager, route: get_page }
            - { name: rest.entity_manager, route: put_pages }
            - { name: rest.entity_manager, route: delete_page }

    engage360d_pages.entity_manager.page:
        class: Doctrine\ORM\EntityManager
        public: false
        factory_service: doctrine
        factory_method: getEntityManager
        arguments: [ ] 
