engage360d_api_pages:
    type:     rest
    resource: Engage360d\Bundle\PagesBundle\Controller\Api\PageController

engage360d_api_categories:
    type:     rest
    resource: Engage360d\Bundle\PagesBundle\Controller\Api\CategoryController

engage360d_api_menus:
    type:     rest
    resource: Engage360d\Bundle\PagesBundle\Controller\Api\MenuController

engage360d_api_url:
    type:     rest
    resource: Engage360d\Bundle\PagesBundle\Controller\Api\UrlController
